project:
  type: website
  output-dir: docs

website:
  title: "javier_si_website"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hobbies.qmd
      - contact.qmd
format:
  html:
    theme: litera
    css: styles.css
    toc: true
    toc-depth: 3
    toc-locatio: left



